---
- name: Deploy to Main K8s Cluster
  hosts: main_cluster
  gather_facts: false
  module_defaults:
    kubernetes.core.k8s:
      kubeconfig: "{{ lookup('env', 'HOME') }}/.kube/config"
      context: "{{ kubeconfig_context }}"
    kubernetes.core.helm:
      kubeconfig: "{{ lookup('env', 'HOME') }}/.kube/config"
      kube_context: "{{ kubeconfig_context }}"
    kubernetes.core.helm_repository:
      kubeconfig: "{{ lookup('env', 'HOME') }}/.kube/config"
  roles:
    - traefik
    - keycloak
    - podinfo

- name: Deploy to Edge Server
  hosts: edge
  gather_facts: false
  module_defaults:
    kubernetes.core.k8s:
      validate_certs: false
      kubeconfig: /var/snap/microk8s/current/credentials/client.config
  roles:
    - prereqs
    - podinfo_edge