all:
  children:
    main_cluster:
      hosts:
        localhost:
          ansible_connection: "{{ connection_env }}"
    edge:
      hosts:
        edge-server:
          ansible_host: "{{ edge_server_name }}"