- name: Check if helm-diff plugin is installed
  ansible.builtin.command: helm plugin list
  register: helm_plugins
  changed_when: false

- name: Install helm-diff plugin
  ansible.builtin.command: helm plugin install https://github.com/databus23/helm-diff --verify=false
  when: "'diff' not in helm_plugins.stdout"

- name: Add Traefik Helm repo
  kubernetes.core.helm_repository:
    name: traefik
    repo_url: https://helm.traefik.io/traefik

- name: Deploy Traefik via Helm
  kubernetes.core.helm:
    name: traefik
    chart_ref: traefik/traefik
    release_namespace: "traefik-{{ env }}"
    create_namespace: true
    chart_version: "{{ components.traefik }}"
    values:
      service:
        type: NodePort
      ports:
        web:
          nodePort: 30080
        websecure:
          nodePort: 30443
      ingressRoute:
        dashboard:
          enabled: false